version: 2

############################################################################

references:
   build_cmd: &build_cmd
      command: |
         source .circleci/get-env.sh;
         ./build.pl \
            --build-type="$ZIMBRA_CI_BUILD_TYPE" \
            --build-hostname="$ZIMBRA_CI_BUILD_HOSTNAME" \
            --build-release="$ZIMBRA_CI_BUILD_RELEASE" \
            --build-release-no="$ZIMBRA_CI_BUILD_RELEASE_NO" \
            --build-release-candidate="$ZIMBRA_CI_BUILD_RELEASE_CANDIDATE" \
            --build-thirdparty-server="$ZIMBRA_CI_THIRDPARTY_SERVER" \
            --deploy-url-prefix="https://$ZIMBRA_CI_DEPLOY_HOSTNAME/$ZIMBRA_CI_DEPLOY_PATH" \
            --git-default-branch="$ZIMBRA_CI_GIT_DEFAULT_BRANCH" \
            "${ZIMBRA_CI_OVERRIDES[@]}" \
            --build-os="$ZIMBRA_BUILD_OS" \
            --build-no="$CIRCLE_BUILD_NUM" \
            --build-ts="$(.circleci/timestamp_hoop.sh)" \
            --no-interactive \
         | tee -a build.log;
         mkdir -p ../BUILDS
         mv build.log ../BUILDS

############################################################################

jobs:
   build_and_deploy_u16:
      working_directory: ~/zm-build
      environment:
         - ZIMBRA_BUILD_OS: UBUNTU16_64
      docker:
         - image: ubuntu:16.04
      steps:
         - checkout
         - run: .circleci/prepare-u16.sh
         - run:
            name: Build
            <<: *build_cmd
         - store_artifacts:
            path: ../BUILDS
         - deploy:
            command: .circleci/deploy-to-s3.sh

   build_and_deploy_u14:
      working_directory: ~/zm-build
      environment:
         - ZIMBRA_BUILD_OS: UBUNTU14_64
      docker:
         - image: ubuntu:14.04
      steps:
         - checkout
         - run: .circleci/prepare-u14.sh
         - run:
            name: Build
            <<: *build_cmd
         - store_artifacts:
            path: ../BUILDS
         - deploy:
            command: .circleci/deploy-to-s3.sh

   build_and_deploy_u12:
      working_directory: ~/zm-build
      environment:
         - ZIMBRA_BUILD_OS: UBUNTU12_64
      docker:
         - image: ubuntu:12.04
      steps:
         - checkout
         - run: .circleci/prepare-u12.sh
         - run:
            name: Build
            <<: *build_cmd
         - store_artifacts:
            path: ../BUILDS
         - deploy:
            command: .circleci/deploy-to-s3.sh

   build_and_deploy_c7:
      working_directory: ~/zm-build
      environment:
         - ZIMBRA_BUILD_OS: RHEL7_64
      docker:
         - image: centos:7
      steps:
         - checkout
         - run: .circleci/prepare-c7.sh
         - run:
            name: Build
            <<: *build_cmd
         - store_artifacts:
            path: ../BUILDS
         - deploy:
            command: .circleci/deploy-to-s3.sh

   build_and_deploy_c6:
      working_directory: ~/zm-build
      environment:
         - ZIMBRA_BUILD_OS: RHEL6_64
      docker:
         - image: centos:6
      steps:
         - checkout
         - run: .circleci/prepare-c6.sh
         - run:
            name: Build
            <<: *build_cmd
         - store_artifacts:
            path: ../BUILDS
         - deploy:
            command: .circleci/deploy-to-s3.sh

############################################################################

workflows:
   version: 2
   build_and_deploy:
      jobs:
         - build_and_deploy_u16
#         - build_and_deploy_u14
#         - build_and_deploy_u12
#         - build_and_deploy_c7
#         - build_and_deploy_c6
